name: update tzdata

permissions:
  contents: read  # workflow-level default: read-only

on:
  schedule:
    # Runs at midnight on the first day of every month in UTC
    - cron: '0 0 1 * *'
  # Optional: Allows manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    permissions:
      contents: write  # only THIS job gets write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6 # Use the actions/checkout action to access your code
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6 # Recommended action for Go environment setup
        with:
          go-version: 1.25.0
          cache: true # Enables intelligent caching for Go modules and build outputs

      #### not needed for now hopefully
      # - name: Download Go modules
      #   run: go mod download

      - name: Build project
        run: go build -o lutz cmd/main.go # Builds the project

      
      - name: Run lutz binary
        run: |
          ./lutz

      - name: Check for changes
        id: check-changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        if: steps.check-changes.outputs.has_changes == 'true'
        with:
          commit_message: Apply automatic changes # Custom commit message
          branch: ${{ github.ref_name }}